/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ae.template;

import ae.ui.fo.*;

/**
 *
 * @author Aditya
 */
public class Template extends javax.swing.JFrame {

    /**
     * Creates new form FO4_PendaftaranEO
     */
    public Template() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_kanan = new javax.swing.JPanel();
        base_kanan = new javax.swing.JLabel();
        panel_kiri = new javax.swing.JPanel();
        base_kiri = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        icon_form = new javax.swing.JPanel();
        lbl_iconform = new javax.swing.JLabel();
        base_panel_main = new javax.swing.JLabel();
        panel_atas = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();
        panel_bawah = new javax.swing.JPanel();
        lbl_footer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_kanan.setPreferredSize(new java.awt.Dimension(200, 550));
        panel_kanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_kanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/panel_kanan.png"))); // NOI18N
        panel_kanan.add(base_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 210, -1));

        getContentPane().add(panel_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, -1, -1));

        panel_kiri.setPreferredSize(new java.awt.Dimension(200, 550));
        panel_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        base_kiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/panel_kiri.png"))); // NOI18N
        panel_kiri.add(base_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        panel_main.setPreferredSize(new java.awt.Dimension(800, 550));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_form.setPreferredSize(new java.awt.Dimension(510, 260));
        icon_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_iconform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/ikon_form.png"))); // NOI18N
        icon_form.add(lbl_iconform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_main.add(icon_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        base_panel_main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/panel_main.png"))); // NOI18N
        panel_main.add(base_panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        panel_atas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/ex2.png"))); // NOI18N
        lbl_header.setPreferredSize(new java.awt.Dimension(1200, 100));
        panel_atas.add(lbl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        getContentPane().add(panel_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        panel_bawah.setPreferredSize(new java.awt.Dimension(1200, 50));
        panel_bawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/footer.png"))); // NOI18N
        lbl_footer.setPreferredSize(new java.awt.Dimension(1200, 50));
        panel_bawah.add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/panel_kiri.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 200, 550));

        setBounds(0, 0, 1216, 739);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Template.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Template().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base_kanan;
    private javax.swing.JLabel base_kiri;
    private javax.swing.JLabel base_panel_main;
    private javax.swing.JPanel icon_form;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_iconform;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_bawah;
    private javax.swing.JPanel panel_kanan;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JPanel panel_main;
    // End of variables declaration//GEN-END:variables
}
