/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ae.ui.fo;

import ae.config.configuration;
import ae.dao.api.ILoginDao;
import ae.model.Login;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ae.ui.bo.Frm1_Menu;

/**
 *
 * @author Aditya
 */
public class FO2_Login_Phase3 extends javax.swing.JFrame {

    /**
     * Creates new form FO2_Login
     */
    public FO2_Login_Phase3() {
        initComponents();
        initLoginDao();
        adm_username.requestFocus();
    }
    private ILoginDao loginDao = null;

    private void initLoginDao() {
        String url = "rmi://" + configuration.ip_server + ":1099/loginDao";
        try {
            //ambil referensi dari remote objek yang ada di server
            loginDao = (ILoginDao) Naming.lookup(url);
        } catch (NotBoundException ex) {
            Logger.getLogger(FO2_Login_Phase3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(FO2_Login_Phase3.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            //Logger.getLogger(FrmSupplier.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Koneksi ke Service" + url + "[GAGAL], cek kembali app server", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adm_username = new javax.swing.JTextField();
        adm_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JLabel();
        lbl_panel_login = new javax.swing.JLabel();
        lbl_ikonemployee = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amikom Event");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(adm_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 365, 320, 40));

        adm_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(adm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 320, 40));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_login.png"))); // NOI18N
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, -1));

        lbl_panel_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/panel_login.png"))); // NOI18N
        getContentPane().add(lbl_panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        lbl_ikonemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/ikon_employee.png"))); // NOI18N
        getContentPane().add(lbl_ikonemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/Background.png"))); // NOI18N
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        if (adm_username.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Input Your Username", "Sign In Error", JOptionPane.ERROR_MESSAGE);
            adm_username.requestFocus();
        } else if (adm_password.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Input Your Password", "Sign In Error", JOptionPane.ERROR_MESSAGE);
            adm_password.requestFocus();
        } else {
            Login logins = new Login();
            logins.setUsername(adm_username.getText());
            logins.setPassword(adm_password.getText());
            try {
                int hasil = loginDao.loginadm(logins);
                if (hasil == 1) {
                    JOptionPane.showMessageDialog(null, "Sign In Success", "Sign-In Success", JOptionPane.INFORMATION_MESSAGE);
                    adm_username.setText("");
                    adm_password.setText("");
                    Frm1_Menu MenuAdm = new Frm1_Menu();
                    MenuAdm.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Password or Username Does Not Match", "Sign-In Error", JOptionPane.ERROR_MESSAGE);
                    adm_username.setText("");
                    adm_password.setText("");
                    adm_username.requestFocus();
                }
            } catch (RemoteException ex) {
                Logger.getLogger(FO2_Login_Phase3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FO2_Login_Phase3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adm_password;
    private javax.swing.JTextField adm_username;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_ikonemployee;
    private javax.swing.JLabel lbl_panel_login;
    // End of variables declaration//GEN-END:variables
}
