/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ae.ui.fo;

/**
 *
 * @author YOPI
 */
public class FO2_Login_Phase2 extends javax.swing.JFrame {

    /**
     * Creates new form FO2_Login_Phase2
     */
    public FO2_Login_Phase2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_admin = new javax.swing.JLabel();
        btn_op = new javax.swing.JLabel();
        lbl_ikon_adm = new javax.swing.JLabel();
        lbl_ikon_op = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amikom Event");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_admin.png"))); // NOI18N
        btn_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adminMouseClicked(evt);
            }
        });
        getContentPane().add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, -1, -1));

        btn_op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_operator.png"))); // NOI18N
        btn_op.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_op.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opMouseClicked(evt);
            }
        });
        getContentPane().add(btn_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        lbl_ikon_adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/OpAdm.png"))); // NOI18N
        getContentPane().add(lbl_ikon_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        lbl_ikon_op.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/OpAdm.png"))); // NOI18N
        getContentPane().add(lbl_ikon_op, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/Background.png"))); // NOI18N
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opMouseClicked
        // TODO add your handling code here:
        FO3_Menu Menu = new FO3_Menu();
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_opMouseClicked

    private void btn_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adminMouseClicked
        // TODO add your handling code here:
        FO2_Login_Phase3 LoginPhase3 = new FO2_Login_Phase3();
        LoginPhase3.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FO2_Login_Phase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FO2_Login_Phase2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_admin;
    private javax.swing.JLabel btn_op;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_ikon_adm;
    private javax.swing.JLabel lbl_ikon_op;
    // End of variables declaration//GEN-END:variables
}
