/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ae.ui.fo;

/**
 *
 * @author Aditya
 */
public class FO3_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FO1_Landing_Page
     */
    public FO3_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main_menu = new javax.swing.JPanel();
        lbl_menu3 = new javax.swing.JLabel();
        lbl_menu2 = new javax.swing.JLabel();
        lbl_menu1 = new javax.swing.JLabel();
        btn_3_listevent = new javax.swing.JLabel();
        btn_2_pendaftaranevent = new javax.swing.JLabel();
        btn_1_pendaftaran_eo = new javax.swing.JLabel();
        lbl_main_menu = new javax.swing.JLabel();
        panel_bawah = new javax.swing.JPanel();
        lbl_footer = new javax.swing.JLabel();
        panel_atas = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amikom Event");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_menu3.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        lbl_menu3.setForeground(new java.awt.Color(88, 48, 88));
        lbl_menu3.setText("List Event / Kegiatan");
        panel_main_menu.add(lbl_menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, -1, -1));

        lbl_menu2.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        lbl_menu2.setForeground(new java.awt.Color(88, 48, 88));
        lbl_menu2.setText("Pendaftaran Event / Kegiatan");
        panel_main_menu.add(lbl_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        lbl_menu1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        lbl_menu1.setForeground(new java.awt.Color(88, 48, 88));
        lbl_menu1.setText("Pendaftaran Event Organizer");
        panel_main_menu.add(lbl_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        btn_3_listevent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_3_listevent.png"))); // NOI18N
        btn_3_listevent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_main_menu.add(btn_3_listevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, -1, -1));

        btn_2_pendaftaranevent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_2_pendaftaranevent.png"))); // NOI18N
        btn_2_pendaftaranevent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_2_pendaftaranevent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_2_pendaftaraneventMouseClicked(evt);
            }
        });
        panel_main_menu.add(btn_2_pendaftaranevent, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        btn_1_pendaftaran_eo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_1_pendaftaran_eo.png"))); // NOI18N
        btn_1_pendaftaran_eo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_1_pendaftaran_eo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_1_pendaftaran_eoMouseClicked(evt);
            }
        });
        panel_main_menu.add(btn_1_pendaftaran_eo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        lbl_main_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/bg_menu_upd.png"))); // NOI18N
        panel_main_menu.add(lbl_main_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_main_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1200, 550));

        panel_bawah.setPreferredSize(new java.awt.Dimension(1200, 50));
        panel_bawah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/footer.png"))); // NOI18N
        panel_bawah.add(lbl_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1200, -1));

        panel_atas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/header1.png"))); // NOI18N
        panel_atas.add(lbl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_atas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1_pendaftaran_eoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1_pendaftaran_eoMouseClicked
        // TODO add your handling code here:
        FO4_PendaftaranEO PendaftaranEO = new FO4_PendaftaranEO();
        PendaftaranEO.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_1_pendaftaran_eoMouseClicked

    private void btn_2_pendaftaraneventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2_pendaftaraneventMouseClicked
        // TODO add your handling code here:
        FO5_PendaftaranEvent PendaftaranEvent = new FO5_PendaftaranEvent();
        PendaftaranEvent.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_2_pendaftaraneventMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FO3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FO3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FO3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FO3_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FO3_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_1_pendaftaran_eo;
    private javax.swing.JLabel btn_2_pendaftaranevent;
    private javax.swing.JLabel btn_3_listevent;
    private javax.swing.JLabel lbl_footer;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_main_menu;
    private javax.swing.JLabel lbl_menu1;
    private javax.swing.JLabel lbl_menu2;
    private javax.swing.JLabel lbl_menu3;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_bawah;
    private javax.swing.JPanel panel_main_menu;
    // End of variables declaration//GEN-END:variables
}
