/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ae.ui.bo;

import ae.config.configuration;
import ae.dao.api.IPeralatanDao;
import ae.model.Peralatan;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aditya
 */
public class Frm5_Peralatan extends javax.swing.JFrame {

    /**
     * Creates new form Frm_SignUp_User
     */
    public Frm5_Peralatan() {
        initComponents();
        init_Peralatan_Dao();
        init_TablePeralatan();
        init_Peralatan_ID();
        loadDaftarPeralatan();
    }

    private DefaultTableModel tabmode;
    private IPeralatanDao peralatanDao = null;
    private final Object[] DaftarPeralatancolumNames = {"ID Peralatan", "Nama Peralatan", "Jumlah"};
    private final DefaultTableModel tableModelPeralatan = new DefaultTableModel();
    private List<Peralatan> recordPeralatan = new ArrayList<Peralatan>();

    private void init_Peralatan_Dao() {
        String url = "rmi://" + configuration.ip_server + ":1099/peralatanDao";
        try {
            //ambil referensi dari remote objek yang ada di server
            peralatanDao = (IPeralatanDao) Naming.lookup(url);
        } catch (NotBoundException | MalformedURLException ex) {
            Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            //Logger.getLogger(FrmSupplier.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Koneksi ke Service" + url + "[GAGAL], cek kembali app server", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void init_TablePeralatan() {
        //set header table
        tableModelPeralatan.setColumnIdentifiers(DaftarPeralatancolumNames);
        tbl_peralatan.setModel(tableModelPeralatan);
        tbl_peralatan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void init_Peralatan_ID() {
        Peralatan P = new Peralatan();
        try {
            String hasil = peralatanDao.GenerateIDPeralatan(P);
            if (hasil == null) {
                //do something
            } else {
                txt_id_peralatan.setText(hasil);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDaftarPeralatan() {
        try {
            // reset data di tabel
            tableModelPeralatan.setRowCount(0);
            // mengambil data barang dari server
            // kemudian menyimpannya ke objek list
            recordPeralatan = peralatanDao.getAll();
            // ekstrak data barang yg ada di dalam objek list
            // kemudian menampilkannya ke objek tabel
            for (Peralatan P : recordPeralatan) {
                // ambil nomor urut terakhir
                Object[] objects = new Object[DaftarPeralatancolumNames.length];
                objects[0] = P.getPeralatan_id();
                objects[1] = P.getPeralatan_nama();
                objects[2] = P.getPeralatan_jumlah();
                // tambahkan data barang ke dalam tabel
                tableModelPeralatan.addRow(objects);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void ClearFormPeralatan() {
        txt_nama_alat.setText("");
        txt_kuantitas.setText("");
        init_Peralatan_ID();
        txt_nama_alat.requestFocus();

        init_TablePeralatan();
        loadDaftarPeralatan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_back = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        btn_reset = new javax.swing.JLabel();
        btn_save = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_peralatan = new javax.swing.JTable();
        txt_kuantitas = new javax.swing.JTextField();
        txt_nama_alat = new javax.swing.JTextField();
        txt_id_peralatan = new javax.swing.JTextField();
        Bg_Pendaftaran_User = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amikom Event");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_kembali2.png"))); // NOI18N
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 530, -1, -1));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_hapus.png"))); // NOI18N
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, -1, -1));

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_update.png"))); // NOI18N
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, -1));

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_reset3.png"))); // NOI18N
        btn_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, -1, -1));

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/btn_simpan5.png"))); // NOI18N
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        tbl_peralatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_peralatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_peralatanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_peralatan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 760, 320));
        getContentPane().add(txt_kuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 250, 30));
        getContentPane().add(txt_nama_alat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 250, 30));

        txt_id_peralatan.setEnabled(false);
        getContentPane().add(txt_id_peralatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 250, 30));

        Bg_Pendaftaran_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ae/image/bg_peralatan.png"))); // NOI18N
        getContentPane().add(Bg_Pendaftaran_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Kembali Ke Menu ?", "Information", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {

            Frm1_Menu Menu = new Frm1_Menu();
            Menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        // TODO add your handling code here:
        ClearFormPeralatan();
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:

        if (txt_nama_alat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tambahkan Nama Peralatan", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (txt_kuantitas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tambahkan Kuantitas Peralatan", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Peralatan P = new Peralatan();
            P.setPeralatan_id(txt_id_peralatan.getText());
            P.setPeralatan_nama(txt_nama_alat.getText());
            int jumlah = Integer.parseInt(txt_kuantitas.getText());
            P.setPeralatan_jumlah(jumlah);
            try {
                int hasil = peralatanDao.saveDataPeralatan(P);
                if (hasil == 1) {
                    JOptionPane.showMessageDialog(null, "Save Data Success", "Save Success", JOptionPane.INFORMATION_MESSAGE);
                    ClearFormPeralatan();
                } else {
                    evt.consume();
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Save Data Failed", "Save Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        Peralatan P = new Peralatan();
        P.setPeralatan_id(txt_id_peralatan.getText());
        P.setPeralatan_nama(txt_nama_alat.getText());
        P.setPeralatan_jumlah(Integer.parseInt(txt_kuantitas.getText()));
        try {
            int hasil = peralatanDao.deletePeralatan(P);
            if (hasil == 1) {
                JOptionPane.showMessageDialog(null, "Hapus Data Success", "Save Success", JOptionPane.INFORMATION_MESSAGE);
                ClearFormPeralatan();
            } else {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Hapus Data Failed", "Save Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void tbl_peralatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_peralatanMouseClicked
        // TODO add your handling code here:
        int baris = tbl_peralatan.getSelectedRow();
        int kolom = tbl_peralatan.getSelectedColumn();
        String ID = tbl_peralatan.getValueAt(baris, 0).toString();
        String NamaKategori = tbl_peralatan.getValueAt(baris, 1).toString();
        String Jumlah = tbl_peralatan.getValueAt(baris, 2).toString();

        txt_id_peralatan.setText(ID);
        txt_nama_alat.setText(NamaKategori);
        txt_kuantitas.setText(Jumlah);
    }//GEN-LAST:event_tbl_peralatanMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        // TODO add your handling code here:
        Peralatan P = new Peralatan();
        P.setPeralatan_id(txt_id_peralatan.getText());
        P.setPeralatan_nama(txt_nama_alat.getText());
        P.setPeralatan_jumlah(Integer.parseInt(txt_kuantitas.getText()));
        try {
            int hasil = peralatanDao.updatePeralatan(P);
            if (hasil == 1) {
                JOptionPane.showMessageDialog(null, "Update Data Sukses", "Save Success", JOptionPane.INFORMATION_MESSAGE);
                ClearFormPeralatan();
            } else {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Update Data Gagal", "Save Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Frm5_Peralatan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm5_Peralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm5_Peralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm5_Peralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm5_Peralatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm5_Peralatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg_Pendaftaran_User;
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_peralatan;
    private javax.swing.JTextField txt_id_peralatan;
    private javax.swing.JTextField txt_kuantitas;
    private javax.swing.JTextField txt_nama_alat;
    // End of variables declaration//GEN-END:variables
}
